# Generated by Django 4.1.7 on 2023-04-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_digital',
            new_name='digital',
        ),
    ]
