# Generated by Django 4.1.7 on 2023-04-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
